### PR TITLE
Feature/Routing and App layout

### LINKED ISSUE #21: Route components
Let's work on routing the component screens already and check it out on the electron perspective

### PR DESCRIPTION
**Pull request by isotopeee**
closes #21 

I've already set up the navigation structure, _Protected Routes_, and created the app layout/skeleton. Sorry it took quite time ✌️

### CODE REVIEW

**Comment by jmaicaaan** [comment]
Hey @isotopeee , great work! Nothing so serious changes to be made. Tested also the electron app. Looks amazing. I like the left sidebar 🔥 

Can we add a title of "Menus" there? See attached image!
image
And also if it's not too much work. Can we add the selected menu highlighted? 

Let me know your thoughts! Thanks for the work!

**Comment by jmaicaaan** [comment]
Oops, the menu title in the left-sidebar doesn't quite look good. 
Let's only add the feature for the selected menu highlighted. 

Btw, how do you develop in the electron? `yarn start-main-dev` or `start-renderer-dev` seems to not working on my end.

**Comment by isotopeee** [comment]
Hi, @jmaicaaan. I've implemented the requested change. I start the electron app in dev mode using `yarn dev`.

**Comment by jmaicaaan** [comment]
Looks good! @isotopeee

**Pull request merged**
