### PR TITLE
#1: Initial setup

### LINKED ISSUE #1: Initial setup
- [x] Update README
- [x] Update `package.json`
- [x] Add and integrate `material-ui`
- [x] Add and integrate `storybook`
- [x] Add and integrate `storyshots`
- [x] Snapshot tests
- [x] Components stories
- [x] Migrate to `fractal` file structure
- [x] Remove `counter` app related files
- [x] Remove `font-awesome`
- [x] Include roboto font

### PR DESCRIPTION
**Pull request by isotopeee**
Closes #1: Initial setup

The `flow` type system is already included in this PR but I haven't used it yet. I've used the `prop-types` package to enforce type checking.

### CODE REVIEW

**Comment by isotopeee** [comment]
I've migrated the file structure to follow the `Fractal` pattern: https://hackernoon.com/fractal-a-react-app-structure-for-infinite-scale-4dab943092af. In my own opinion, I think it's a good structure but let me know what you think.

**Review by jmaicaaan — CHANGES_REQUESTED** [review]
As part of the initial setup, let's remove the files related to `Counter` to reduce boilerplate.

Also, why do we app two `package.json`? One in the root and one inside the `app` folder?

Storybooks work well btw 😉

**Comment by isotopeee** [comment]
Hi @jmaicaaan, I assume you already know why there are two `package.json`. I've already cleaned up the files related to the `Counter` app included in the boilerplate. You can check out the changes. I'm also planning to include the set up of `Roboto` font which I can't accomplish now because of network issues. If you found out more issues, feel free to comment. Thanks!

**Comment by jmaicaaan** [comment]
Yes, I've seen it in the documentation. Thank you for the update. Will wait for your next changes as you've mentioned above.

**Review by jmaicaaan — APPROVED** [review]

**Pull request merged**
